wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/all.KL.bed.multires.mv5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/Dixon2012-J1-NcoI-R1-filtered.100kb.multires.cool
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/hic-resolutions.cool
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/sample_htime.json
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/gene_annotations.short.db
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/wgEncodeCaltechRnaSeqHuvecR1x75dTh1014IlnaPlusSignalRep2.bigWig
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/points_density.h5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/int_matrices.hdf5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/corrected.geneListwithStrand.bed.multires
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/labels.h5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.sorted.short.bam
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.different_index_filename.bai
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.sorted.short.bam.bai
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.mismatched_bai.bam
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/geneAnnotationsExonUnions.1000.bed.v3.beddb
wget -q -NP data/ https://s3.amazonaws.com/areynolds/public/masterlist_DHSs_733samples_WM20180608_all_mean_signal_colorsMax.bed.bb
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/states_format_input_testfile.100.bed.multires.mv5