wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/chromSizes.tsv
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/all.KL.bed.multires.mv5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/Dixon2012-J1-NcoI-R1-filtered.100kb.multires.cool
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/hic-resolutions.cool
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/sample_htime.json
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/gene_annotations.short.db
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/wgEncodeCaltechRnaSeqHuvecR1x75dTh1014IlnaPlusSignalRep2.bigWig
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/points_density.h5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/int_matrices.hdf5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/corrected.geneListwithStrand.bed.multires
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/labels.h5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.sorted.short.bam
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.different_index_filename.bai
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.sorted.short.bam.bai
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.mismatched_bai.bam
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/geneAnnotationsExonUnions.1000.bed.v3.beddb
wget -q -NP data/ https://s3.amazonaws.com/areynolds/public/masterlist_DHSs_733samples_WM20180608_all_mean_signal_colorsMax.bed.bb
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/states_format_input_testfile.100.bed.multires.mv5
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/GCA_000350705.1_Esch_coli_KTE11_V1_genomic.short.fna.fai
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/GCA_002918705.1_ASM291870v1_genomic.gff.gz
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/genomic.10k.gff.gz
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/chm13v1.chrom.sizes
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/hg38.chrom.sizes
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/test.1.vcf.gz
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/no_item_rgb.bed
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/regions.valid.bed.1.gz
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/regions.valid.bed
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/genomic.10k.gff.gz.tbi
wget -q -NP data/ https://resgen-public.s3.amazonaws.com/clodius/test-data/GCA_000350705.1_Esch_coli_KTE11_V1_genomic.short.fna
