wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/all.KL.bed.multires.mv5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/Dixon2012-J1-NcoI-R1-filtered.100kb.multires.cool
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/hic-resolutions.cool
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/sample_htime.json
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/gene_annotations.short.db
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/wgEncodeCaltechRnaSeqHuvecR1x75dTh1014IlnaPlusSignalRep2.bigWig
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/points_density.h5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/int_matrices.hdf5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/corrected.geneListwithStrand.bed.multires
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/labels.h5
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.sorted.short.bam
wget -q -NP data/ https://s3.amazonaws.com/pkerp/public/SRR1770413.sorted.short.bam.bai
